artifact_location: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/models/m-bd9f112ec1374e27a06a0f9f6e0dc3a1/artifacts
creation_timestamp: 1789540369430
experiment_id: '0'
last_updated_timestamp: 1789540371321
model_id: m-bd9f112ec1374e27a06a0f9f6e0dc3a1
model_type: null
name: model
source_run_id: 4997099969a84a65ba0d9bbae4406ad7
status: 2
status_message: null
