artifact_uri: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/5d68933a445148ffbc7eae920ee64451/artifacts
end_time: 1789540329720
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5d68933a445148ffbc7eae920ee64451
run_name: debonair-fox-817
source_name: ''
source_type: 4
source_version: ''
start_time: 1789540329704
status: 4
tags: []
user_id: apeksha-ssi021
