artifact_uri: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/4997099969a84a65ba0d9bbae4406ad7/artifacts
end_time: 1789540371324
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4997099969a84a65ba0d9bbae4406ad7
run_name: calm-hawk-559
source_name: ''
source_type: 4
source_version: ''
start_time: 1789540369333
status: 3
tags: []
user_id: apeksha-ssi021
