artifact_uri: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/d6af9803b9bb405eaea650e926659f5e/artifacts
end_time: 1789540191552
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d6af9803b9bb405eaea650e926659f5e
run_name: rumbling-midge-14
source_name: ''
source_type: 4
source_version: ''
start_time: 1789540191534
status: 4
tags: []
user_id: apeksha-ssi021
