artifact_uri: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/915c236990d645c6b7dcd2894a5f06e2/artifacts
end_time: 1789540369320
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 915c236990d645c6b7dcd2894a5f06e2
run_name: caring-crane-410
source_name: ''
source_type: 4
source_version: ''
start_time: 1789540369308
status: 4
tags: []
user_id: apeksha-ssi021
