artifact_uri: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/9bcb0b0094914058adb27a473a95b75b/artifacts
end_time: 1789539918136
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9bcb0b0094914058adb27a473a95b75b
run_name: able-gnat-114
source_name: ''
source_type: 4
source_version: ''
start_time: 1789539918125
status: 4
tags: []
user_id: apeksha-ssi021
