# Generated by Django 6.1.1 on 2026-09-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_format", models.CharField(max_length=20)),
                ("file_size", models.PositiveBigIntegerField()),
                ("status", models.CharField(default="PENDING", max_length=50)),
                (
                    "mlflow_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mlflow_version", models.IntegerField(blank=True, null=True)),
                ("run_id", models.CharField(blank=True, max_length=255, null=True)),
                ("model_uri", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
