# Generated by Django 5.2.17 on 2026-09-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedmodel',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
