# Generated by Django 5.2.17 on 2026-09-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_importedmodel_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedmodel',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='architecture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='deployment_points',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='is_deployable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='model_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importedmodel',
            name='versioning',
            field=models.CharField(default='Auto-increment', max_length=50),
        ),
    ]
