creation_timestamp: 1789540371338
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1789540371338
model_id: m-bd9f112ec1374e27a06a0f9f6e0dc3a1
name: test_onnx_final
run_id: 4997099969a84a65ba0d9bbae4406ad7
run_link: null
source: models:/m-bd9f112ec1374e27a06a0f9f6e0dc3a1
status: READY
status_message: null
storage_location: /home/apeksha-ssi021/Shyena/integrated_model/mlflow_registration/backend/<YOUR_MLFLOW_TRACKING_URI>/0/models/m-bd9f112ec1374e27a06a0f9f6e0dc3a1/artifacts
user_id: null
version: 1
workspace: default
